spring:
  profiles:
    active: local
  application:
    name: phone-country-app
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:postgresql://db:5432/phonecountry
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8088

phone:
  country:
    api-url: https://en.wikipedia.org/wiki/List_of_telephone_country_codes#Alphabetical_order
    connection-timeout: 5000
    read-timeout: 5000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
